/**
 * MOTIF
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Alert
 */
export interface Alert { 
    /**
     * alert id
     */
    id?: number;
    /**
     * title
     */
    title?: string;
    /**
     * description
     */
    description?: string;
    /**
     * Creation date and time
     */
    date?: string;
    /**
     * alert priority
     */
    priority?: number;
    /**
     * Alert type
     */
    type?: Alert.TypeEnum;
    /**
     * Alert style
     */
    style?: Alert.StyleEnum;
    /**
     * alert seen
     */
    seen?: boolean;
    /**
     * user username
     */
    user?: string;
}
export namespace Alert {
    export type TypeEnum = 'BASIC' | 'HELP_REQUEST';
    export const TypeEnum = {
        Basic: 'BASIC' as TypeEnum,
        HelpRequest: 'HELP_REQUEST' as TypeEnum
    };
    export type StyleEnum = 'BASIC' | 'WARNING' | 'INFORMATION';
    export const StyleEnum = {
        Basic: 'BASIC' as StyleEnum,
        Warning: 'WARNING' as StyleEnum,
        Information: 'INFORMATION' as StyleEnum
    };
}


