/**
 * MOTIF
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HelpRequest } from './helpRequest';


/**
 * Help requests
 */
export interface HelpRequestPage { 
    /**
     * Total number of pages
     */
    totalNumberOfPages: number;
    /**
     * Total number of pages
     */
    totalNumberOfElements: number;
    /**
     * Retrieved requests
     */
    requests: Array<HelpRequest>;
}

